name: Build and Release

# Trigger the workflow when a new release is created or when a tag is pushed
on:
  release:
    types: [created]
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Go 1.x (use the version you need)
    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.2

    # Cache Go modules to speed up builds
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    # Install dependencies
    - name: Install dependencies
      run: go mod download

    # Build the Go binary
    - name: Build binary
      run: go build -o bin/ssm-env

    # Upload the built binary as a release asset
    - name: Upload binary to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./bin/ssm-env
        asset_name: ssm-env
        asset_content_type: application/octet-stream
